### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by jenniferemshepherd** [jenniferemshepherd/dawn#1]
- choose dependencies and install
- update README.md to document how to do so

**Comment by rcvink** [comment]
* [Node.js](https://nodejs.org/en/).
* [NPM](https://www.npmjs.com/) for dependencies.
* [Matter.js](http://brm.io/matter-js/) for physics, with the following plugins:
  * [matter-attractors](https://github.com/liabru/matter-attractors)
  * [matter-collision-events](https://github.com/dxu/matter-collision-events)
* [p5-sound](https://p5js.org/reference/#/libraries/p5.sound) for sound.
* [React.js](https://reactjs.org/) for UI.
* [Jasmine](https://jasmine.github.io/) for unit and integration testing.
* [Nightwatch.js](http://nightwatchjs.org/) for front-end UI testing.
* [webpack](https://webpack.js.org/) for bundling on deployment.
