### ISSUE TITLE
improve file structure

### ISSUE THREAD

**Issue by jenniferemshepherd** [jenniferemshepherd/dawn#69]

**Comment by rcvink** [comment]
https://github.com/jenniferemshepherd/dawn/wiki/Folder-structure

**Comment by rcvink** [comment]
In PR #131 I have already relocated all of the listeners to a /listeners folder.

Still to-do:
- Move and rename `ColourInheritor` to the /inheritors folder.
- Move and rename all `decorator` modules to a /decorators folder.
- Move and rename `Simulation` and `EventController` to a /controllers folder.

I'd also suggest:
- A /services folder for modules like `Mutator` and `RgbFormatter` which don't fit well into other categories?
